### ISSUE TITLE
QT_BREAKDOWN_PATH value for Age is inconsistent with PCORNET_DEMO c_fullname values

### ISSUE THREAD

**Issue by ConnieZ** [ARCH-commons/arch-ontology#70]
There is an inconsistency in pcornet_demo vs. qt_breakdown_path table for Age paths:
- pcornet_demo table has Age c_fullname values start with "\PCORI\DEMOGRAPHIC\Age\..."
- qt_breakdown_path table has value "\PCORI_DEMO\PCORI\DEMOGRAPHIC\AGE\"
That difference in case could be responsible for the "Error executing QueryResultPatientSetGenerator.generateResult:null" we get on the i2b2 side when querying i2b2 or SHRINE for Age breakdowns.

We checked that the default i2b2 QT_BREAKDOWN_PATH table creation has this statement:
insert into QT_BREAKDOWN_PATH(NAME,VALUE,CREATE_DATE) values ('PATIENT_AGE_COUNT_XML','\i2b2_DEMO\i2b2\Demographics\Age\',now());
Which is consistent with the c_fullname path values in the default i2b2 ontology table

Please review and resolve if possible. Thanks.

**Comment by jklann** [comment]
Let's just change qt_breakdown path to "\PCORI_DEMO\PCORI\DEMOGRAPHIC\Age". Matt can you make this change in the repo?

**Comment by jklann** [comment]
Fixed with commit d96ad75a46f01b2a25982b5fb99d98c380d2845b
