### ISSUE TITLE
create sql server metadata tables needs updating

### ISSUE THREAD

**Issue by matthewjoss** [ARCH-commons/arch-ontology#75]
the file found here needs to be updated:
https://github.com/ARCH-commons/arch-ontology/blob/master/Scripts/SqlServer/create_sqlserver_metadata_tables.sql

It appears to not be up to date with regards to what is needed for OMOP. For example demo is missing imaps and PCORI_SOURCECODE.

**Comment by jklann** [comment]
Looks like you already did this in issue #62 in August. I don't think anything else needs to be done to the ontology for OMOP right now.

**Comment by matthewjoss** [comment]
I think we must have added things since then because I noticed that the existing script in Github does not have OMOP_basecode or i_flags for the demo table, both of which are columns that exist in the copy you uploaded to the dropbox. So in order to import those tables correctly into our eMERGE project I needed to make a new DDL for that. I already did this actually, just have not pushed it up to github yet.
