### ISSUE TITLE
pcornet_enc: IN instead of LIKE for c_fullname = '\PCORI\ENCOUNTER\VERSION\'

### ISSUE THREAD

**Issue by ConnieZ** [ARCH-commons/arch-ontology#80]
Bug was fixed in official SCILHS PCORI ontology repo on GitHub per this commit: https://github.com/SCILHS/scilhs-ontology/commit/861fb094c843f45081db686ab6578b7734e0e326, with comment "c_operator issue in pcornet_enc table fixed by changing 'IN' to 'LIKE…' in metadata"

However, the latest version of ontology now has it as 'IN' again. This bug is still present in internally, and we were going to have this fixed with this version, but now it would be different from the source.

Is this intentional? Should we just keep it as is?

**Comment by jklann** [comment]
This issue is only applicable to queryable terms, and Version is not queryable. Either IN or LIKE are acceptable. Closing this.
